using System.Globalization;
using System.Net;
using System.Text;

namespace Illumin360.Recruitment.Application.Recruitment;

/// <summary>
/// Renders a formal, printable employment-offer letter as self-contained HTML, including the terms and an
/// e-signature block (typed name + timestamp when signed, or an "awaiting signature" note otherwise). All
/// dynamic values are HTML-encoded.
/// </summary>
public static class OfferLetterHtml
{
    /// <summary>Renders the offer letter for the given offer.</summary>
    /// <param name="offer">The offer to render.</param>
    /// <param name="brand">The issuing brand/organisation name.</param>
    /// <returns>A complete HTML document.</returns>
    public static string Render(OfferDto offer, string brand)
    {
        ArgumentNullException.ThrowIfNull(offer);
        var b = Enc(brand);
        var title = Enc(offer.Title);
        var salary = $"{Enc(offer.Currency)} {offer.SalaryAmount.ToString("N2", CultureInfo.InvariantCulture)}";
        var issued = offer.CreatedAt.UtcDateTime.ToString("d MMMM yyyy", CultureInfo.InvariantCulture);
        var signed = offer.Status == "accepted" && !string.IsNullOrWhiteSpace(offer.SignedByName);

        var sb = new StringBuilder();
        sb.Append("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.Append(CultureInfo.InvariantCulture, $"<title>Offer letter — {title}</title>");
        sb.Append("<style>");
        sb.Append("*{box-sizing:border-box}body{margin:0;background:#f4f6f5;color:#12211b;font:15px/1.65 Georgia,'Times New Roman',serif}");
        sb.Append(".sheet{max-width:720px;margin:32px auto;background:#fff;padding:56px 64px;border-radius:6px;box-shadow:0 2px 18px rgba(0,0,0,.08)}");
        sb.Append(".brand{font-family:system-ui,sans-serif;font-weight:800;letter-spacing:-.01em;font-size:22px;color:#12211b}");
        sb.Append(".date{color:#5a6b62;font-family:system-ui,sans-serif;font-size:13px;margin-top:4px}");
        sb.Append("h1{font-size:22px;margin:32px 0 8px}dl{display:grid;grid-template-columns:180px 1fr;gap:8px 16px;margin:24px 0}dt{color:#5a6b62;font-family:system-ui,sans-serif;font-size:13px}dd{margin:0;font-weight:600}");
        sb.Append(".sig{margin-top:40px;border-top:1px solid #d8e0dc;padding-top:24px;font-family:system-ui,sans-serif}.sig .name{font-size:20px;font-family:'Segoe Script','Brush Script MT',cursive;color:#12211b}.muted{color:#5a6b62;font-size:13px;font-family:system-ui,sans-serif}");
        sb.Append("</style></head><body><main class=\"sheet\">");
        sb.Append(CultureInfo.InvariantCulture, $"<div class=\"brand\">{b}</div><div class=\"date\">Issued {Enc(issued)}</div>");
        sb.Append(CultureInfo.InvariantCulture, $"<h1>Offer of employment: {title}</h1>");
        sb.Append(CultureInfo.InvariantCulture, $"<p>Dear Candidate,</p><p>We are pleased to offer you the position of <strong>{title}</strong> at {b}. The key terms of your offer are set out below.</p>");
        sb.Append("<dl>");
        sb.Append(CultureInfo.InvariantCulture, $"<dt>Position</dt><dd>{title}</dd>");
        sb.Append(CultureInfo.InvariantCulture, $"<dt>Annual salary</dt><dd>{Enc(salary)}</dd>");
        sb.Append(CultureInfo.InvariantCulture, $"<dt>Start date</dt><dd>{Enc(offer.StartDate)}</dd>");
        sb.Append("</dl>");
        if (!string.IsNullOrWhiteSpace(offer.Notes))
        {
            sb.Append(CultureInfo.InvariantCulture, $"<p>{Enc(offer.Notes)}</p>");
        }

        sb.Append("<p>To accept this offer, please sign electronically below.</p>");
        sb.Append("<div class=\"sig\">");
        if (signed)
        {
            var when = offer.SignedAt?.UtcDateTime.ToString("d MMMM yyyy, HH:mm 'UTC'", CultureInfo.InvariantCulture) ?? string.Empty;
            sb.Append(CultureInfo.InvariantCulture, $"<div class=\"name\">{Enc(offer.SignedByName)}</div><div class=\"muted\">Signed electronically on {Enc(when)}</div>");
        }
        else
        {
            sb.Append("<div class=\"muted\">Awaiting the candidate's electronic signature.</div>");
        }

        sb.Append("</div>");
        sb.Append(CultureInfo.InvariantCulture, $"<p class=\"muted\" style=\"margin-top:40px\">{b} · Generated by Illumin360</p>");
        sb.Append("</main></body></html>");
        return sb.ToString();
    }

    private static string Enc(string? value) => WebUtility.HtmlEncode(value ?? string.Empty);
}
