<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Illumin360.Recruitment.Api</RootNamespace>
    <UserSecretsId>illumin360-recruitment</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" />
    <ProjectReference Include="..\Illumin360.Recruitment.Application\Illumin360.Recruitment.Application.csproj" />
    <ProjectReference Include="..\Illumin360.Recruitment.Infrastructure\Illumin360.Recruitment.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Observability\Illumin360.Observability.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Web\Illumin360.Web.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Security\Illumin360.Security.csproj" />
  </ItemGroup>
</Project>
